### ISSUE TITLE
Limitations of WGLMakie backend (tracking issue)

### ISSUE THREAD

**Issue by kbarros** [SunnySuite/Sunny.jl#211]
[WGLMakie](https://docs.makie.org/stable/explanations/backends/wglmakie) loads interactive graphics inside a web context. It can be useful with Jupyter notebooks, or for remote Sunny sessions where a GLMakie connection isn't possible. However, support for WGLMakie is still maturing. If you encounter graphics issues, consider `using GLMakie` instead for a more reliable experience.

Major outstanding problems with WGLMakie:

- [ ] Incompatibility with many Jupyter notebook environments (https://github.com/MakieOrg/Makie.jl/issues/3769). IJulia is compatible, but others (like the VSCode notebook browser) are not.

Would be nice to have:

- [ ] https://github.com/MakieOrg/Makie.jl/issues/4103.
- [ ] https://github.com/MakieOrg/Makie.jl/issues/3773.

Many other problems have been resolved or mitigated:

- [x] ~~Inconsistent activation of widgets (https://github.com/MakieOrg/Makie.jl/issues/3752).~~
- [x] ~~Missing fonts for some characters (https://github.com/MakieOrg/Makie.jl/issues/3516).~~
- [x] ~~https://github.com/MakieOrg/Makie.jl/pull/3722~~
- [x] ~~Mouse-over lines does not give reliable information (https://github.com/MakieOrg/Makie.jl/issues/3672)~~ 
- [x] ~~Cannot vendor WGLMakie custom fonts~~ A  workaround is to select from the [Makie built-in fonts](https://github.com/MakieOrg/Makie.jl/tree/0e28ea88a7cdae4a6161893e60b93aa9321baaab/assets/fonts).
- [x] ~~Interactive WGLMakie figure throws errors (https://github.com/MakieOrg/Makie.jl/issues/3781). See issue comments for remaining bugs, which seem linked to Bonito.~~
- [x] ~~https://github.com/SunnySuite/Sunny.jl/issues/290.~~

**Comment by quantumsteve** [comment]
Another nice to have #347
